baseURL = "https://frankliu.org/hugo/"
# relativeURLs = true
# uglyURLs = true
languageCode = "en-us"
title = "My New Hugo Site"
theme = "ananke"
pygmentsCodeFences = true
# pygmentsUseClasses = true
# pygmentsUseClassic = false
canonifyURLs = true