baseURL = "https://www.frankliu.org/hugo/"
# relativeURLs = true
# uglyURLs = true
languageCode = "en-us"
title = "My New Hugo Site"
theme = "ananke"
pygmentsCodeFences = true
# pygmentsUseClasses = true
# pygmentsUseClassic = false
canonifyURLs = true

[author]
	name = "Frankie Liu"

