baseURL = "https://www.frankliu.org/hugo/"
# relativeURLs = true
# uglyURLs = true
languageCode = "en-us"
title = "My New Hugo Site"
theme = "ananke"
pygmentsCodeFences = true
# pygmentsUseClasses = true
# pygmentsUseClassic = false
canonifyURLs = true
SectionPagesMenu = "main"

[params]
    facebook = "https://www.facebook.com/frankie.liu.9279"
    twitter = "https://twitter.com/pi31415629"
    github = "https://github.com/frankieliu"
    linkedin = "https://www.linkedin.com/in/frankieyliu/"
    discord = "https://discordapp.com/users/523372803387293696"
    medium = "https://medium.com/eins-zwei"
		custom_css = [ "/css/_social-icons.css" ]
		
